FROM python:3.9-slim-buster

ARG DEBIAN_FRONTEND=noninteractive

COPY ./ ./TenSEAL
WORKDIR /TenSEAL

RUN .github/workflows/scripts/install_req_docker.sh

ENV CC=clang \
    CXX=clang++

RUN pip3 install .

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" TZ="Europe/Stockholm" apt-get install -y python3 python3-pip npm wget vim git
RUN pip3 install jupyterlab pandas numpy scipy notebook
RUN npm install --global yarn
RUN jupyter notebook --generate-config

ENV JUPYTER_TOKEN secret
CMD ["jupyter", "lab", "--allow-root", "--ip", "0.0.0.0", "--notebook-dir", "/notebooks"]
